### ISSUE TITLE
Local Development

### ISSUE THREAD

**Issue by ALLiDoizCode** [levifeldman/ic_tools_dart#1]
I don't see an option that lets you point to your local replica for development

**Comment by levifeldman** [comment]
Good-point. Version: 1.0.3 out now, you can set the icbaseurl variable and it is now a Uri type. Now if someone wants they to find and set the host and port of the IC by them selves then they can.

**Comment by levifeldman** [comment]
https://github.com/levifeldman/ic_tools_dart/blob/master/CHANGELOG.md#103
